require("presence").setup {
  auto_update = true,
  neovim_image_text = "Help! Can't exit this wonderful editor :(",
  main_image = "file",
  log_level = nil,
  debounce_timeout = 10,
  enable_line_number = false,
  blacklist = {
    "NvimTree",
    "nvdash",
    "nvcheatsheet",
    "terminal",
    "Trouble",
    "help",
    "man",
    "prompt",
  },
  buttons = { { label = "just click don't ask", url = "https://www.youtube.com/watch?v=C3GouGa0noM" } },
  show_time = true,
  editing_text = "making spaghetti in %s",
  file_explorer_text = "searching %s",
  git_commit_text = "ready to screw up the main branch",
  plugin_manager_text = "taking care of this masterpiece",
  reading_text = "reading? %s",
  workspace_text = "working on %s",
  line_number_text = "at line %s out of %s",
}
